name: Release NodeJS app 

on:
  push:
    branches:
      - main

jobs:

  publish-docker-hub:
    
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    
    steps:
    # Checkout to the repo
    - uses: actions/checkout@v3

    # We need to login so we can later push the image without issues.
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: flyingstickdevops/express-app:latest
